const contents=
[   {texts:"this is content writen by salman this blog content is displalying to hte user dynamically using the small khnowledge of javascript Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium, optio dolor? Molestiae repudiandae praesentium dolore, officiis odio ad sit iure qui impedit aperiam. Dignissimos nemo hic aperiam optio nulla distinctio consequuntur nam, facilis rem dicta sit ratione commodi porro iste aliquam, tenetur accusantium doloribus nt ab unde debitis nisi id deleniti? Mollitia ullam animi vero, praesentium sit veniam tempora omnis numquam fugiat odit consectetur iure rem laborum sunt blanditiis quis soluta officia explicabo neque libero eos vel labore totam provident. Perspiciatis esse, sequi odio quod officiis excepturi natus? Consectetur ipsum excepturi facilis, laborum odit aliquam natus distinctio quia exercitationem aut eum. Laborum, repelle temporibus rerum quisquam provident quae eveniet, vel fugit, similique officia. Minima doloremque non, dolor eum aperiam officia quo nam qui repudiandae praesentium veniam corporis nulla dolorem vero dicta explicabo soluta! Ex atque magni illum dignissimos delectus nisi nostrum praesentium modi eius a odit, nihil harum maiores recusandae distinctio? Repellat eius inventore quibusdam, ex velit quo corrupti? Dolores officiis rep",img:'shop'},
    {texts:"this is content writen by mukul this blog content is displalying to hte user dynamically using the small khnowledge of javascript Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium, optio dolor? Molestiae repudiandae praesentium dolore, officiis odio ad sit iure qui impedit aperiam. Dignissimos nemo hic aperiam optio nulla distinctio consequuntur nam, facilis rem dicta sit ratione commodi porro iste aliquam, tenetur accusantium doloribus nt ab unde debitis nisi id deleniti? Mollitia ullam animi vero, praesentium sit veniam tempora omnis numquam fugiat odit consectetur iure rem laborum sunt blanditiis quis soluta officia explicabo neque libero eos vel labore totam provident. Perspiciatis esse, sequi odio quod officiis excepturi natus? Consectetur ipsum excepturi facilis, laborum odit aliquam natus distinctio quia exercitationem aut eum. Laborum, repelle temporibus rerum quisquam provident quae eveniet, vel fugit, similique officia. Minima doloremque non, dolor eum aperiam officia quo nam qui repudiandae praesentium veniam corporis nulla dolorem vero dicta explicabo soluta! Ex atque magni illum dignissimos delectus nisi nostrum praesentium modi eius a odit, nihil harum maiores recusandae distinctio? Repellat eius inventore quibusdam, ex velit quo corrupti? Dolores officiis rep",img:'medi'},
    {texts:"this is content writen by priyanshu this blog content is displalying to hte user dynamically using the small khnowledge of javascript Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium, optio dolor? Molestiae repudiandae praesentium dolore, officiis odio ad sit iure qui impedit aperiam. Dignissimos nemo hic aperiam optio nulla distinctio consequuntur nam, facilis rem dicta sit ratione commodi porro iste aliquam, tenetur accusantium doloribus nt ab unde debitis nisi id deleniti? Mollitia ullam animi vero, praesentium sit veniam tempora omnis numquam fugiat odit consectetur iure rem laborum sunt blanditiis quis soluta officia explicabo neque libero eos vel labore totam provident. Perspiciatis esse, sequi odio quod officiis excepturi natus? Consectetur ipsum excepturi facilis, laborum odit aliquam natus distinctio quia exercitationem aut eum. Laborum, repelle temporibus rerum quisquam provident quae eveniet, vel fugit, similique officia. Minima doloremque non, dolor eum aperiam officia quo nam qui repudiandae praesentium veniam corporis nulla dolorem vero dicta explicabo soluta! Ex atque magni illum dignissimos delectus nisi nostrum praesentium modi eius a odit, nihil harum maiores recusandae distinctio? Repellat eius inventore quibusdam, ex velit quo corrupti? Dolores officiis rep",img:'spg'},
    {texts:"this is content writen by arham this blog content is displalying to hte user dynamically using the small khnowledge of javascript Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium, optio dolor? Molestiae repudiandae praesentium dolore, officiis odio ad sit iure qui impedit aperiam. Dignissimos nemo hic aperiam optio nulla distinctio consequuntur nam, facilis rem dicta sit ratione commodi porro iste aliquam, tenetur accusantium doloribus nt ab unde debitis nisi id deleniti? Mollitia ullam animi vero, praesentium sit veniam tempora omnis numquam fugiat odit consectetur iure rem laborum sunt blanditiis quis soluta officia explicabo neque libero eos vel labore totam provident. Perspiciatis esse, sequi odio quod officiis excepturi natus? Consectetur ipsum excepturi facilis, laborum odit aliquam natus distinctio quia exercitationem aut eum. Laborum, repelle temporibus rerum quisquam provident quae eveniet, vel fugit, similique officia. Minima doloremque non, dolor eum aperiam officia quo nam qui repudiandae praesentium veniam corporis nulla dolorem vero dicta explicabo soluta! Ex atque magni illum dignissimos delectus nisi nostrum praesentium modi eius a odit, nihil harum maiores recusandae distinctio? Repellat eius inventore quibusdam, ex velit quo corrupti? Dolores officiis rep",img:'blog'},
    {texts:"this is content writen by shiv this blog content is displalying to hte user dynamically using the small khnowledge of javascript Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium, optio dolor? Molestiae repudiandae praesentium dolore, officiis odio ad sit iure qui impedit aperiam. Dignissimos nemo hic aperiam optio nulla distinctio consequuntur nam, facilis rem dicta sit ratione commodi porro iste aliquam, tenetur accusantium doloribus nt ab unde debitis nisi id deleniti? Mollitia ullam animi vero, praesentium sit veniam tempora omnis numquam fugiat odit consectetur iure rem laborum sunt blanditiis quis soluta officia explicabo neque libero eos vel labore totam provident. Perspiciatis esse, sequi odio quod officiis excepturi natus? Consectetur ipsum excepturi facilis, laborum odit aliquam natus distinctio quia exercitationem aut eum. Laborum, repelle temporibus rerum quisquam provident quae eveniet, vel fugit, similique officia. Minima doloremque non, dolor eum aperiam officia quo nam qui repudiandae praesentium veniam corporis nulla dolorem vero dicta explicabo soluta! Ex atque magni illum dignissimos delectus nisi nostrum praesentium modi eius a odit, nihil harum maiores recusandae distinctio? Repellat eius inventore quibusdam, ex velit quo corrupti? Dolores officiis rep",img:'girl'},
    {texts:"this is content writen by rohit this blog content is displalying to hte user dynamically using the small khnowledge of javascript Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium, optio dolor? Molestiae repudiandae praesentium dolore, officiis odio ad sit iure qui impedit aperiam. Dignissimos nemo hic aperiam optio nulla distinctio consequuntur nam, facilis rem dicta sit ratione commodi porro iste aliquam, tenetur accusantium doloribus nt ab unde debitis nisi id deleniti? Mollitia ullam animi vero, praesentium sit veniam tempora omnis numquam fugiat odit consectetur iure rem laborum sunt blanditiis quis soluta officia explicabo neque libero eos vel labore totam provident. Perspiciatis esse, sequi odio quod officiis excepturi natus? Consectetur ipsum excepturi facilis, laborum odit aliquam natus distinctio quia exercitationem aut eum. Laborum, repelle temporibus rerum quisquam provident quae eveniet, vel fugit, similique officia. Minima doloremque non, dolor eum aperiam officia quo nam qui repudiandae praesentium veniam corporis nulla dolorem vero dicta explicabo soluta! Ex atque magni illum dignissimos delectus nisi nostrum praesentium modi eius a odit, nihil harum maiores recusandae distinctio? Repellat eius inventore quibusdam, ex velit quo corrupti? Dolores officiis rep",img:'ai'},
    {texts:"this is content writen by vivan this blog content is displalying to hte user dynamically using the small khnowledge of javascript Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusantium, optio dolor? Molestiae repudiandae praesentium dolore, officiis odio ad sit iure qui impedit aperiam. Dignissimos nemo hic aperiam optio nulla distinctio consequuntur nam, facilis rem dicta sit ratione commodi porro iste aliquam, tenetur accusantium doloribus nt ab unde debitis nisi id deleniti? Mollitia ullam animi vero, praesentium sit veniam tempora omnis numquam fugiat odit consectetur iure rem laborum sunt blanditiis quis soluta officia explicabo neque libero eos vel labore totam provident. Perspiciatis esse, sequi odio quod officiis excepturi natus? Consectetur ipsum excepturi facilis, laborum odit aliquam natus distinctio quia exercitationem aut eum. Laborum, repelle temporibus rerum quisquam provident quae eveniet, vel fugit, similique officia. Minima doloremque non, dolor eum aperiam officia quo nam qui repudiandae praesentium veniam corporis nulla dolorem vero dicta explicabo soluta! Ex atque magni illum dignissimos delectus nisi nostrum praesentium modi eius a odit, nihil harum maiores recusandae distinctio? Repellat eius inventore quibusdam, ex velit quo corrupti? Dolores officiis rep",img:'puspa'}
]

function shower(contents)
{
    let len= contents.length;
    let p=document.getElementById("showing");
    let postimg= document.getElementById("postimage");
    let i = Math.floor(Math.random()*len);
    let obj= contents[i];
    p.textContent= obj.texts;
    postimg.src=`../images/${obj.img}.jpg`;   
}

shower(contents);